Repository openshift/egress-router-cni, pull requests merged in 2021-02, with the labels that each got.

#27 Bug 1913011: Add default route through macvlan interface
  pkg/macvlan/macvlan.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#33 Bug 1924985: Build binaries for both RHEL 7 and 8
  Dockerfile.rhel8
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#29 Update README to current implementation
  README.md
Labels: approved, lgtm

#34 SDN-1569: Add support for multiple destinations in redirect mode
  pkg/macvlan/macvlan.go
Labels: approved, lgtm
